title:              "PortfolioFuture"
email:              chenqijunvc@gmail.com
description:        "Exploring AI, Data, and Finance - Investment analysis, strategies, and market commentary by Vince Qijun Chen."
author:             Vince Qijun Chen
# For root domain (chenqijunvc.github.io), baseurl should be empty
baseurl:            ""
url:                "https://chenqijunvc.github.io"

# SEO and Social
keywords:           "quantitative finance, machine learning, AI, investment strategy, portfolio management, data science"
lang:               "en"
locale:             "en_US"

# Social Profiles
twitter_username:   # Your Twitter username when available
github_username:    chenqijunvc
linkedin_username:  vinceqijunchen

# Analytics - Replace with your actual Google Analytics 4 ID
# google_analytics:   G-XXXXXXXXXX

# Author information for structured data
author_info:
  name:             "Vince Qijun Chen"
  bio:              "Quantitative analyst and data scientist specializing in AI applications in finance"
  location:         "Global"
  expertise:        ["Quantitative Finance", "Machine Learning", "Data Science", "Portfolio Management"]

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"

# URL structure - no trailing slashes
permalink:          /:title/

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap # Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Collections
collections:
  media:
    output: true
    permalink: /media/:title/

# Dynamic background images
default_backgrounds:
  home: '/img/bg-index.jpg'
  about: '/img/bg-about.jpg'
  posts: '/img/bg-post.jpg'
  contact: '/img/bg-contact.jpg'
  search: '/img/bg-post.jpg'
  default: '/img/bg-post.jpg'

# Category-specific backgrounds (will fallback to defaults if these don't exist)
category_backgrounds:
  ai: '/img/bg-post.jpg'
  finance: '/img/bg-post.jpg'
  data-science: '/img/bg-post.jpg'
  investment-strategy: '/img/bg-post.jpg'