title:              "Vince Qijun Chen"
email:              chenqijunvc@gmail.com
description:        "Portfolio Manager & Quantamental Strategist - Specializing in free cash flow investing, ETF strategy development, and systematic investment approaches."
author:             Vince Qijun Chen
# For root domain (chenqijunvc.github.io), baseurl should be empty
baseurl:            ""
url:                "https://chenqijunvc.github.io"

# SEO and Social
keywords:           "Vince Qijun Chen, portfolio manager, quantamental investing, free cash flow, FCF-ROIC, ETF strategy, ABFL, ABLS, ABOT, CBOE, investment management"
lang:               "en"
locale:             "en_US"

# Social Profiles
twitter_username:   # Your Twitter username when available
github_username:    chenqijunvc
linkedin_username:  vinceqijunchen

# Analytics - Replace with your actual Google Analytics 4 ID
# google_analytics:   G-XXXXXXXXXX

# Author information for structured data
author_info:
  name:             "Vince Qijun Chen"
  bio:              "Portfolio manager and quantamental strategist specializing in free cash flow investing and ETF strategy development"
  location:         "Global"
  expertise:        ["Free Cash Flow Investing", "ETF Strategy", "Quantamental Analysis", "Portfolio Management", "Financial Media"]

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"

# URL structure - no trailing slashes
permalink:          /:title/

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap # Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Collections
collections:
  media:
    output: true
    permalink: /media/:title/

# Dynamic background images
default_backgrounds:
  home: '/img/bg-index.jpg'
  about: '/img/bg-about.jpg'
  posts: '/img/bg-post.jpg'
  contact: '/img/bg-contact.jpg'
  search: '/img/bg-post.jpg'
  default: '/img/bg-post.jpg'

# Category-specific backgrounds (will fallback to defaults if these don't exist)
category_backgrounds:
  ai: '/img/bg-post.jpg'
  finance: '/img/bg-post.jpg'
  data-science: '/img/bg-post.jpg'
  investment-strategy: '/img/bg-post.jpg'